# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'revide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for revide
  pod 'Material', '2.9.0'
  pod 'Graph', '~> 2.0'
  pod 'MobilePlayer'
  pod 'ReSwift'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SwiftyJSON'

  target 'revideTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'revideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
